version: '3.8'

services:
  npm: &npm
    image: node:12.16
    volumes:
      - ./:/devstronomy/ui
      - cache-node_modules:/devstronomy/ui/node_modules
    entrypoint: npm
    working_dir: /devstronomy/ui

  ui-install-deps:
    <<: *npm
    command: install

  dev-server:
    <<: *npm
    command: start
    stdin_open: true
    ports:
      - '3000:3000'

volumes:
  cache-node_modules:
